from tkinter import *

root=Tk()
root.geometry('500x400')
root.config(bg="sky blue")

root.title("Registration Page")
label1=Label(root,text="Registration Page",bg="green",fg="white")
label1.grid(row=0,column=2)
name=Label(root,text="Name:-",justify=LEFT,bg="sky blue",fg="white")
name.grid(row=2,column=0)
name_entry=Entry(root)
name_entry.grid(row=2,column=2)
branch=Label(root,text="Branch:-",justify=LEFT,bg="sky blue",fg="white")
branch.grid(row=4,column=0)
branch_entry=Entry(root)
branch_entry.grid(row=4,column=2)
address=Label(root,text="Address:-",justify=LEFT,bg="sky blue",fg="white")
address.grid(row=6,column=0)
address_entry=Entry(root)
address_entry.grid(row=6,column=2)
age=Label(root,text="Age:-",justify=LEFT,bg="sky blue",fg="white")
age.grid(row=8,column=0)
age_entry=Entry(root)
age_entry.grid(row=8,column=2)
gender=Label(root,text="Gender:-",justify=LEFT,bg="sky blue",fg="white")
gender.grid(row=10,column=0)
male=Radiobutton(root,text="Male",justify=LEFT,bg="sky blue",fg="white")
male.grid(row=10,column=2)
female=Radiobutton(root,text="Female",justify=LEFT,bg="sky blue",fg="white")
female.grid(row=10,column=4)
nationality=Label(root,text="Nationality:-",justify=LEFT,bg="sky blue",fg="white")
nationality.grid(row=12,column=0)
indian=Checkbutton(root,text="Indian",justify=LEFT,bg="sky blue",fg="white")
indian.grid(row=12,column=2)
nri=Checkbutton(root,text="Nri",justify=LEFT,bg="sky blue",fg="white")
nri.grid(row=12,column=4)
tick=Label(root,text="(please tick correctly)",justify=LEFT,bg="sky blue",fg="white")
tick.grid(row=13,column=0)
phone=Label(root,text="Contact No.:-",justify=LEFT,bg="sky blue",fg="white")
phone.grid(row=14,column=0)
phone_entry=Entry(root)
phone_entry.grid(row=14,column=2)
mail=Label(root,text="E-mail:-",justify=LEFT,bg="sky blue",fg="white")
mail.grid(row=16,column=0)
mail_entry=Entry(root)
mail_entry.grid(row=16,column=2)
c1=Checkbutton(root,justify=LEFT,bg="sky blue",fg="white")
c1.grid(row=17,column=0)
terms=Label(root,text="I agree to terms and conditions",justify=LEFT,bg="sky blue",fg="white")
terms.grid(row=17,column=2)
c2=Checkbutton(root,justify=LEFT,bg="sky blue",fg="white")
c2.grid(row=19,column=0)
privacy=Label(root,text="I agree to privacy and policy",justify=LEFT,bg="sky blue",fg="white")
privacy.grid(row=19,column=2)
submit=Button(root,text="Submit",justify=LEFT,bg="red",fg="white")
submit.grid(row=20,column=2)
root.mainloop()